#!/bin/bash
freespace=$(df -h / | grep -E "\/$" | awk '{print $4}')
greentext="\033[32m"
bold="\033[1m"
normal="\033[0m"
logdate=$(date +"%Y%m%d")
logfile="$logdate"_report.log

echo -e $bold"Quick system report for "$greentext"$HOSTNAME"$normal
printf "\tSystem type:\t%s\n" $MACHTYPE
printf "\tBash Version:\t%s\n" $BASH_VERSION
printf "\tFree Space:\t%s\n" $freespace
printf "\tFiles in dir:\t%s\n" $(ls | wc -l) # wc = wordcount
printf "\tGenerated on:\t%s\n" $(date +"%d/%m/%Y") # date format
echo -e $greentext"A summary of this info has been saved to $logfile"$normal

# heredoc + dodavanje > u fajl
cat <<- EOF > $logfile
  This report was automatically generated by my Bash script.
  It contains a brief summary of some system information.
EOF

# APPEND eof
printf "SYS:\t%s\n" $MACHTYPE >> $logfile
printf "BASH:\t%s\n" $BASH_VERSION >> $logfile

